FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine:edge AS build
RUN apk add --no-cache \
    crystal \
    shards \
    yaml-static \
    zlib-static \
    gc-static \
    pcre2-static \
    make
